# Change Tmux prefix key to Ctrl-t
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

# Bind Ctrl-s to toggle statusline without prefix
bind-key -n C-b set-option -g status #Ctrl+s Combo

# Switch panes Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind k confirm kill-session
bind K confirm kill-server
bind f run-shell "tmux neww 'zsh ~/.config/zsh/tmux-find-files.zsh'"
bind D run-shell "tmux neww 'zsh ~/.config/zsh/tmux-find-dirs.zsh'"

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
unbind '"'
unbind %

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Change windows base config
setw -g automatic-rename

# Change windows base config
set -g base-index 1

# Ensure window index numbers get reordered on delete
set-option -g renumber-windows on
set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Change terminal colors
set -s default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

# Change escape time
set -s escape-time 0

# Turn status on
set -g status on

# Update the status line every second
set -g status-interval 1

# Set the position of window lists.
set -g status-justify left # [left | centre | right]

# Set Vi style keybinding in the status line
# set -g status-keys vi
# set-window-option -g mode-keys vi
# Set the status bar position
set -g status-position bottom # [top, bottom]

# Set status bar background and foreground color.
set -g status-style fg=white,bg="#282C34"

# Status Left
set -g status-left-length 60
set -g status-left-style default
set -g status-left "#[fg=cyan] ❐ #S #[default]"

# Status Right
set -g status-right-length 60
set -g status-right-style default
set -g status-right "#[fg=white,bg=default] ⌚%l:%M %p #[default]"
set -ag status-right "#[fg=white,bg=default]| 📅 %a %d #[default]"

# Set the inactive window color and style
# set -g window-status-style fg=white,bg="#282C34"
set -g window-status-style fg=white,bg="#282C34"
set -g window-status-format ' #I #W '

# Set the active window color and style
set -g window-status-current-style fg=black,bg=green
set -g window-status-current-format ' #I #W '

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-sensible' <- I'm not even sure what this does

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/.tmux/plugins/tpm/tpm'
